/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedCuentasRouteImport } from './routes/_authenticated/cuentas'
import { Route as AuthenticatedEscaladoRouteImport } from './routes/_authenticated/escalado'
import { Route as AuthenticatedEstrategiasRouteImport } from './routes/_authenticated/estrategias'
import { Route as AuthenticatedIntegracionesRouteImport } from './routes/_authenticated/integraciones'
import { Route as AuthenticatedOperacionesRouteImport } from './routes/_authenticated/operaciones'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedRetirosRouteImport } from './routes/_authenticated/retiros'
import { Route as ApiPublicTradesWebhookRouteImport } from './routes/api/public/trades.webhook'

const AuthenticatedCuentasRoute = AuthenticatedCuentasRouteImport.update({
  id: '/_authenticated/cuentas',
  path: '/cuentas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEscaladoRoute = AuthenticatedEscaladoRouteImport.update({
  id: '/_authenticated/escalado',
  path: '/escalado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEstrategiasRoute =
  AuthenticatedEstrategiasRouteImport.update({
    id: '/_authenticated/estrategias',
    path: '/estrategias',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedIntegracionesRoute =
  AuthenticatedIntegracionesRouteImport.update({
    id: '/_authenticated/integraciones',
    path: '/integraciones',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOperacionesRoute =
  AuthenticatedOperacionesRouteImport.update({
    id: '/_authenticated/operaciones',
    path: '/operaciones',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/_authenticated/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRetirosRoute = AuthenticatedRetirosRouteImport.update({
  id: '/_authenticated/retiros',
  path: '/retiros',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTradesWebhookRoute = ApiPublicTradesWebhookRouteImport.update({
  id: '/api/public/trades/webhook',
  path: '/api/public/trades/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/cuentas': typeof AuthenticatedCuentasRoute
  '/escalado': typeof AuthenticatedEscaladoRoute
  '/estrategias': typeof AuthenticatedEstrategiasRoute
  '/integraciones': typeof AuthenticatedIntegracionesRoute
  '/operaciones': typeof AuthenticatedOperacionesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/retiros': typeof AuthenticatedRetirosRoute
  '/api/public/trades/webhook': typeof ApiPublicTradesWebhookRoute
}
export interface FileRoutesByTo {
  '/cuentas': typeof AuthenticatedCuentasRoute
  '/escalado': typeof AuthenticatedEscaladoRoute
  '/estrategias': typeof AuthenticatedEstrategiasRoute
  '/integraciones': typeof AuthenticatedIntegracionesRoute
  '/operaciones': typeof AuthenticatedOperacionesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/retiros': typeof AuthenticatedRetirosRoute
  '/api/public/trades/webhook': typeof ApiPublicTradesWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/cuentas': typeof AuthenticatedCuentasRoute
  '/_authenticated/escalado': typeof AuthenticatedEscaladoRoute
  '/_authenticated/estrategias': typeof AuthenticatedEstrategiasRoute
  '/_authenticated/integraciones': typeof AuthenticatedIntegracionesRoute
  '/_authenticated/operaciones': typeof AuthenticatedOperacionesRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/retiros': typeof AuthenticatedRetirosRoute
  '/api/public/trades/webhook': typeof ApiPublicTradesWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/cuentas'
    | '/escalado'
    | '/estrategias'
    | '/integraciones'
    | '/operaciones'
    | '/panel'
    | '/retiros'
    | '/api/public/trades/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cuentas'
    | '/escalado'
    | '/estrategias'
    | '/integraciones'
    | '/operaciones'
    | '/panel'
    | '/retiros'
    | '/api/public/trades/webhook'
  id:
    | '__root__'
    | '/_authenticated/cuentas'
    | '/_authenticated/escalado'
    | '/_authenticated/estrategias'
    | '/_authenticated/integraciones'
    | '/_authenticated/operaciones'
    | '/_authenticated/panel'
    | '/_authenticated/retiros'
    | '/api/public/trades/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedCuentasRoute: typeof AuthenticatedCuentasRoute
  AuthenticatedEscaladoRoute: typeof AuthenticatedEscaladoRoute
  AuthenticatedEstrategiasRoute: typeof AuthenticatedEstrategiasRoute
  AuthenticatedIntegracionesRoute: typeof AuthenticatedIntegracionesRoute
  AuthenticatedOperacionesRoute: typeof AuthenticatedOperacionesRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedRetirosRoute: typeof AuthenticatedRetirosRoute
  ApiPublicTradesWebhookRoute: typeof ApiPublicTradesWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/cuentas': {
      id: '/_authenticated/cuentas'
      path: '/cuentas'
      fullPath: '/cuentas'
      preLoaderRoute: typeof AuthenticatedCuentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/escalado': {
      id: '/_authenticated/escalado'
      path: '/escalado'
      fullPath: '/escalado'
      preLoaderRoute: typeof AuthenticatedEscaladoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/estrategias': {
      id: '/_authenticated/estrategias'
      path: '/estrategias'
      fullPath: '/estrategias'
      preLoaderRoute: typeof AuthenticatedEstrategiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/integraciones': {
      id: '/_authenticated/integraciones'
      path: '/integraciones'
      fullPath: '/integraciones'
      preLoaderRoute: typeof AuthenticatedIntegracionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/operaciones': {
      id: '/_authenticated/operaciones'
      path: '/operaciones'
      fullPath: '/operaciones'
      preLoaderRoute: typeof AuthenticatedOperacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/retiros': {
      id: '/_authenticated/retiros'
      path: '/retiros'
      fullPath: '/retiros'
      preLoaderRoute: typeof AuthenticatedRetirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trades/webhook': {
      id: '/api/public/trades/webhook'
      path: '/api/public/trades/webhook'
      fullPath: '/api/public/trades/webhook'
      preLoaderRoute: typeof ApiPublicTradesWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedCuentasRoute: AuthenticatedCuentasRoute,
  AuthenticatedEscaladoRoute: AuthenticatedEscaladoRoute,
  AuthenticatedEstrategiasRoute: AuthenticatedEstrategiasRoute,
  AuthenticatedIntegracionesRoute: AuthenticatedIntegracionesRoute,
  AuthenticatedOperacionesRoute: AuthenticatedOperacionesRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedRetirosRoute: AuthenticatedRetirosRoute,
  ApiPublicTradesWebhookRoute: ApiPublicTradesWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
