/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedCuentasRouteImport } from './routes/_authenticated/cuentas'
import { Route as AuthenticatedDiariosRouteImport } from './routes/_authenticated/diarios'
import { Route as AuthenticatedEstrategiasRouteImport } from './routes/_authenticated/estrategias'
import { Route as AuthenticatedMenteRouteImport } from './routes/_authenticated/mente'
import { Route as AuthenticatedOperacionesRouteImport } from './routes/_authenticated/operaciones'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedSupervisionRouteImport } from './routes/_authenticated/supervision'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedCuentaAccountIdRouteImport } from './routes/_authenticated/cuenta.$accountId'
import { Route as ApiPublicTradesWebhookRouteImport } from './routes/api/public/trades.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCuentasRoute = AuthenticatedCuentasRouteImport.update({
  id: '/cuentas',
  path: '/cuentas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiariosRoute = AuthenticatedDiariosRouteImport.update({
  id: '/diarios',
  path: '/diarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstrategiasRoute =
  AuthenticatedEstrategiasRouteImport.update({
    id: '/estrategias',
    path: '/estrategias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenteRoute = AuthenticatedMenteRouteImport.update({
  id: '/mente',
  path: '/mente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperacionesRoute =
  AuthenticatedOperacionesRouteImport.update({
    id: '/operaciones',
    path: '/operaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupervisionRoute =
  AuthenticatedSupervisionRouteImport.update({
    id: '/supervision',
    path: '/supervision',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCuentaAccountIdRoute =
  AuthenticatedCuentaAccountIdRouteImport.update({
    id: '/cuenta/$accountId',
    path: '/cuenta/$accountId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicTradesWebhookRoute = ApiPublicTradesWebhookRouteImport.update({
  id: '/api/public/trades/webhook',
  path: '/api/public/trades/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/chat': typeof AuthenticatedChatRoute
  '/conta': typeof AuthenticatedContaRoute
  '/cuentas': typeof AuthenticatedCuentasRoute
  '/diarios': typeof AuthenticatedDiariosRoute
  '/estrategias': typeof AuthenticatedEstrategiasRoute
  '/mente': typeof AuthenticatedMenteRoute
  '/operaciones': typeof AuthenticatedOperacionesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/supervision': typeof AuthenticatedSupervisionRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/cuenta/$accountId': typeof AuthenticatedCuentaAccountIdRoute
  '/api/public/trades/webhook': typeof ApiPublicTradesWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/chat': typeof AuthenticatedChatRoute
  '/conta': typeof AuthenticatedContaRoute
  '/cuentas': typeof AuthenticatedCuentasRoute
  '/diarios': typeof AuthenticatedDiariosRoute
  '/estrategias': typeof AuthenticatedEstrategiasRoute
  '/mente': typeof AuthenticatedMenteRoute
  '/operaciones': typeof AuthenticatedOperacionesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/supervision': typeof AuthenticatedSupervisionRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/cuenta/$accountId': typeof AuthenticatedCuentaAccountIdRoute
  '/api/public/trades/webhook': typeof ApiPublicTradesWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/cuentas': typeof AuthenticatedCuentasRoute
  '/_authenticated/diarios': typeof AuthenticatedDiariosRoute
  '/_authenticated/estrategias': typeof AuthenticatedEstrategiasRoute
  '/_authenticated/mente': typeof AuthenticatedMenteRoute
  '/_authenticated/operaciones': typeof AuthenticatedOperacionesRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/supervision': typeof AuthenticatedSupervisionRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/cuenta/$accountId': typeof AuthenticatedCuentaAccountIdRoute
  '/api/public/trades/webhook': typeof ApiPublicTradesWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/chat'
    | '/conta'
    | '/cuentas'
    | '/diarios'
    | '/estrategias'
    | '/mente'
    | '/operaciones'
    | '/panel'
    | '/supervision'
    | '/usuarios'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/cuenta/$accountId'
    | '/api/public/trades/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/chat'
    | '/conta'
    | '/cuentas'
    | '/diarios'
    | '/estrategias'
    | '/mente'
    | '/operaciones'
    | '/panel'
    | '/supervision'
    | '/usuarios'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/cuenta/$accountId'
    | '/api/public/trades/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/chat'
    | '/_authenticated/conta'
    | '/_authenticated/cuentas'
    | '/_authenticated/diarios'
    | '/_authenticated/estrategias'
    | '/_authenticated/mente'
    | '/_authenticated/operaciones'
    | '/_authenticated/panel'
    | '/_authenticated/supervision'
    | '/_authenticated/usuarios'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/cuenta/$accountId'
    | '/api/public/trades/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicTradesWebhookRoute: typeof ApiPublicTradesWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cuentas': {
      id: '/_authenticated/cuentas'
      path: '/cuentas'
      fullPath: '/cuentas'
      preLoaderRoute: typeof AuthenticatedCuentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diarios': {
      id: '/_authenticated/diarios'
      path: '/diarios'
      fullPath: '/diarios'
      preLoaderRoute: typeof AuthenticatedDiariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estrategias': {
      id: '/_authenticated/estrategias'
      path: '/estrategias'
      fullPath: '/estrategias'
      preLoaderRoute: typeof AuthenticatedEstrategiasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mente': {
      id: '/_authenticated/mente'
      path: '/mente'
      fullPath: '/mente'
      preLoaderRoute: typeof AuthenticatedMenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operaciones': {
      id: '/_authenticated/operaciones'
      path: '/operaciones'
      fullPath: '/operaciones'
      preLoaderRoute: typeof AuthenticatedOperacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervision': {
      id: '/_authenticated/supervision'
      path: '/supervision'
      fullPath: '/supervision'
      preLoaderRoute: typeof AuthenticatedSupervisionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cuenta/$accountId': {
      id: '/_authenticated/cuenta/$accountId'
      path: '/cuenta/$accountId'
      fullPath: '/cuenta/$accountId'
      preLoaderRoute: typeof AuthenticatedCuentaAccountIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/trades/webhook': {
      id: '/api/public/trades/webhook'
      path: '/api/public/trades/webhook'
      fullPath: '/api/public/trades/webhook'
      preLoaderRoute: typeof ApiPublicTradesWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedCuentasRoute: typeof AuthenticatedCuentasRoute
  AuthenticatedDiariosRoute: typeof AuthenticatedDiariosRoute
  AuthenticatedEstrategiasRoute: typeof AuthenticatedEstrategiasRoute
  AuthenticatedMenteRoute: typeof AuthenticatedMenteRoute
  AuthenticatedOperacionesRoute: typeof AuthenticatedOperacionesRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedSupervisionRoute: typeof AuthenticatedSupervisionRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedCuentaAccountIdRoute: typeof AuthenticatedCuentaAccountIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedCuentasRoute: AuthenticatedCuentasRoute,
  AuthenticatedDiariosRoute: AuthenticatedDiariosRoute,
  AuthenticatedEstrategiasRoute: AuthenticatedEstrategiasRoute,
  AuthenticatedMenteRoute: AuthenticatedMenteRoute,
  AuthenticatedOperacionesRoute: AuthenticatedOperacionesRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedSupervisionRoute: AuthenticatedSupervisionRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedCuentaAccountIdRoute: AuthenticatedCuentaAccountIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicTradesWebhookRoute: ApiPublicTradesWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
