/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCuentasRouteImport } from './routes/_authenticated/cuentas'
import { Route as AuthenticatedDiariosRouteImport } from './routes/_authenticated/diarios'
import { Route as AuthenticatedEscaladoRouteImport } from './routes/_authenticated/escalado'
import { Route as AuthenticatedEstrategiasRouteImport } from './routes/_authenticated/estrategias'
import { Route as AuthenticatedIntegracionesRouteImport } from './routes/_authenticated/integraciones'
import { Route as AuthenticatedOperacionesRouteImport } from './routes/_authenticated/operaciones'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedRetirosRouteImport } from './routes/_authenticated/retiros'
import { Route as AuthenticatedSupervisionRouteImport } from './routes/_authenticated/supervision'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedCuentaAccountIdRouteImport } from './routes/_authenticated/cuenta.$accountId'
import { Route as ApiPublicTradesWebhookRouteImport } from './routes/api/public/trades.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCuentasRoute = AuthenticatedCuentasRouteImport.update({
  id: '/cuentas',
  path: '/cuentas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiariosRoute = AuthenticatedDiariosRouteImport.update({
  id: '/diarios',
  path: '/diarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscaladoRoute = AuthenticatedEscaladoRouteImport.update({
  id: '/escalado',
  path: '/escalado',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstrategiasRoute =
  AuthenticatedEstrategiasRouteImport.update({
    id: '/estrategias',
    path: '/estrategias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegracionesRoute =
  AuthenticatedIntegracionesRouteImport.update({
    id: '/integraciones',
    path: '/integraciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOperacionesRoute =
  AuthenticatedOperacionesRouteImport.update({
    id: '/operaciones',
    path: '/operaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRetirosRoute = AuthenticatedRetirosRouteImport.update({
  id: '/retiros',
  path: '/retiros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupervisionRoute =
  AuthenticatedSupervisionRouteImport.update({
    id: '/supervision',
    path: '/supervision',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCuentaAccountIdRoute =
  AuthenticatedCuentaAccountIdRouteImport.update({
    id: '/cuenta/$accountId',
    path: '/cuenta/$accountId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicTradesWebhookRoute = ApiPublicTradesWebhookRouteImport.update({
  id: '/api/public/trades/webhook',
  path: '/api/public/trades/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRoute
  '/cuentas': typeof AuthenticatedCuentasRoute
  '/diarios': typeof AuthenticatedDiariosRoute
  '/escalado': typeof AuthenticatedEscaladoRoute
  '/estrategias': typeof AuthenticatedEstrategiasRoute
  '/integraciones': typeof AuthenticatedIntegracionesRoute
  '/operaciones': typeof AuthenticatedOperacionesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/retiros': typeof AuthenticatedRetirosRoute
  '/supervision': typeof AuthenticatedSupervisionRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/cuenta/$accountId': typeof AuthenticatedCuentaAccountIdRoute
  '/api/public/trades/webhook': typeof ApiPublicTradesWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRoute
  '/cuentas': typeof AuthenticatedCuentasRoute
  '/diarios': typeof AuthenticatedDiariosRoute
  '/escalado': typeof AuthenticatedEscaladoRoute
  '/estrategias': typeof AuthenticatedEstrategiasRoute
  '/integraciones': typeof AuthenticatedIntegracionesRoute
  '/operaciones': typeof AuthenticatedOperacionesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/retiros': typeof AuthenticatedRetirosRoute
  '/supervision': typeof AuthenticatedSupervisionRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/cuenta/$accountId': typeof AuthenticatedCuentaAccountIdRoute
  '/api/public/trades/webhook': typeof ApiPublicTradesWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/cuentas': typeof AuthenticatedCuentasRoute
  '/_authenticated/diarios': typeof AuthenticatedDiariosRoute
  '/_authenticated/escalado': typeof AuthenticatedEscaladoRoute
  '/_authenticated/estrategias': typeof AuthenticatedEstrategiasRoute
  '/_authenticated/integraciones': typeof AuthenticatedIntegracionesRoute
  '/_authenticated/operaciones': typeof AuthenticatedOperacionesRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/retiros': typeof AuthenticatedRetirosRoute
  '/_authenticated/supervision': typeof AuthenticatedSupervisionRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/cuenta/$accountId': typeof AuthenticatedCuentaAccountIdRoute
  '/api/public/trades/webhook': typeof ApiPublicTradesWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/cuentas'
    | '/diarios'
    | '/escalado'
    | '/estrategias'
    | '/integraciones'
    | '/operaciones'
    | '/panel'
    | '/retiros'
    | '/supervision'
    | '/usuarios'
    | '/cuenta/$accountId'
    | '/api/public/trades/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/cuentas'
    | '/diarios'
    | '/escalado'
    | '/estrategias'
    | '/integraciones'
    | '/operaciones'
    | '/panel'
    | '/retiros'
    | '/supervision'
    | '/usuarios'
    | '/cuenta/$accountId'
    | '/api/public/trades/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/chat'
    | '/_authenticated/cuentas'
    | '/_authenticated/diarios'
    | '/_authenticated/escalado'
    | '/_authenticated/estrategias'
    | '/_authenticated/integraciones'
    | '/_authenticated/operaciones'
    | '/_authenticated/panel'
    | '/_authenticated/retiros'
    | '/_authenticated/supervision'
    | '/_authenticated/usuarios'
    | '/_authenticated/cuenta/$accountId'
    | '/api/public/trades/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicTradesWebhookRoute: typeof ApiPublicTradesWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cuentas': {
      id: '/_authenticated/cuentas'
      path: '/cuentas'
      fullPath: '/cuentas'
      preLoaderRoute: typeof AuthenticatedCuentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diarios': {
      id: '/_authenticated/diarios'
      path: '/diarios'
      fullPath: '/diarios'
      preLoaderRoute: typeof AuthenticatedDiariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escalado': {
      id: '/_authenticated/escalado'
      path: '/escalado'
      fullPath: '/escalado'
      preLoaderRoute: typeof AuthenticatedEscaladoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estrategias': {
      id: '/_authenticated/estrategias'
      path: '/estrategias'
      fullPath: '/estrategias'
      preLoaderRoute: typeof AuthenticatedEstrategiasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integraciones': {
      id: '/_authenticated/integraciones'
      path: '/integraciones'
      fullPath: '/integraciones'
      preLoaderRoute: typeof AuthenticatedIntegracionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operaciones': {
      id: '/_authenticated/operaciones'
      path: '/operaciones'
      fullPath: '/operaciones'
      preLoaderRoute: typeof AuthenticatedOperacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retiros': {
      id: '/_authenticated/retiros'
      path: '/retiros'
      fullPath: '/retiros'
      preLoaderRoute: typeof AuthenticatedRetirosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supervision': {
      id: '/_authenticated/supervision'
      path: '/supervision'
      fullPath: '/supervision'
      preLoaderRoute: typeof AuthenticatedSupervisionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cuenta/$accountId': {
      id: '/_authenticated/cuenta/$accountId'
      path: '/cuenta/$accountId'
      fullPath: '/cuenta/$accountId'
      preLoaderRoute: typeof AuthenticatedCuentaAccountIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/trades/webhook': {
      id: '/api/public/trades/webhook'
      path: '/api/public/trades/webhook'
      fullPath: '/api/public/trades/webhook'
      preLoaderRoute: typeof ApiPublicTradesWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCuentasRoute: typeof AuthenticatedCuentasRoute
  AuthenticatedDiariosRoute: typeof AuthenticatedDiariosRoute
  AuthenticatedEscaladoRoute: typeof AuthenticatedEscaladoRoute
  AuthenticatedEstrategiasRoute: typeof AuthenticatedEstrategiasRoute
  AuthenticatedIntegracionesRoute: typeof AuthenticatedIntegracionesRoute
  AuthenticatedOperacionesRoute: typeof AuthenticatedOperacionesRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedRetirosRoute: typeof AuthenticatedRetirosRoute
  AuthenticatedSupervisionRoute: typeof AuthenticatedSupervisionRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedCuentaAccountIdRoute: typeof AuthenticatedCuentaAccountIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCuentasRoute: AuthenticatedCuentasRoute,
  AuthenticatedDiariosRoute: AuthenticatedDiariosRoute,
  AuthenticatedEscaladoRoute: AuthenticatedEscaladoRoute,
  AuthenticatedEstrategiasRoute: AuthenticatedEstrategiasRoute,
  AuthenticatedIntegracionesRoute: AuthenticatedIntegracionesRoute,
  AuthenticatedOperacionesRoute: AuthenticatedOperacionesRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedRetirosRoute: AuthenticatedRetirosRoute,
  AuthenticatedSupervisionRoute: AuthenticatedSupervisionRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedCuentaAccountIdRoute: AuthenticatedCuentaAccountIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicTradesWebhookRoute: ApiPublicTradesWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
